# Generated by Django 3.1.5 on 2021-01-15 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='date_joinded',
            new_name='date_joined',
        ),
    ]
